#!/bin/bash

ARGS="--param ../Labs/CiberAVLabs/cen-5-cfg.xml"
ARGS+=" --lab ../Labs/CiberAVLabs/cen-5-lab.xml"
ARGS+=" --grid ../Labs/CiberAVLabs/cen-5-grd.xml"
ARGS+=" --beacon"
(cd ../bin; ./simulator $ARGS) &

sleep 1

(cd ../bin; ./Viewer --autoconnect)

killall simulator

sleep 1
