#!/bin/bash

ARGS="--param ../Labs/CiberAVLabs/cen-4-cfg.xml"
ARGS+=" --lab ../Labs/CiberAVLabs/cen-4-lab.xml"
ARGS+=" --grid ../Labs/CiberAVLabs/cen-4-grd.xml"
ARGS+=" --beacon"
ARGS+=" --log /tmp/zzz.log"
(cd ../bin; ./simulator $ARGS) &

sleep 1

(cd ../bin; ./Viewer --autoconnect)

killall simulator

sleep 1
